### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lucasgrocha** [lucasgrocha/dataSensor#1]
### Feature
  - [ ]  Only signed users must see data from sensors
  - [ ] If user is registered as a premium, everyday on morning its gonna receive in his email a chart filled with sensor's data from the last 7 days

### File
 - [ ] Generate data file
     - [ ] CSV
     - [ ] TXT
     - [ ] JSON
     - [ ] XML

### JOB
 - [ ] Use job to generate data file 
 - [ ] Send data file to user's email
 - [ ] Generate data chart everyday on morning

### TOOLS

 - Sidekiq & Redis
 -
